version: '3.8'

services:
  api:
    build: .
    ports:
      - "12000:12000"
    environment:
      - FLASK_ENV=production
      - REDIS_URL=redis://redis:6379/0
      - RATE_LIMIT_STORAGE_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data: